server:
  port: 8003
  servlet:
    context-path: /address

spring:
  application:
    name: cloud-address
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${server.servlet.context-path}/actuator/health