spring:
  rabbitmq:
    host: 172.19.132.25
    port: 35182
    username: guest
    password: guest

  application:
    name: cloud-bus


management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9010
