server:
  port: 7004
  servlet:
    context-path: /order

eureka:
  instance:
    #eureka中实例名称
    instance-id: cloud-order7004
    #eureka中实例IP
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka3001.com:3001/eureka/,http://eureka3002.com:3002/eureka/

spring:
  application:
    name: cloud-order

logging:
  level:
    com.github.cloud.order.feign.AddressRestClient: debug