server:
  port: 7003
  servlet:
    context-path: /order

spring:
  application:
    name: cloud-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${server.servlet.context-path}/actuator/health