server:
  port: 8005
  servlet:
    context-path: /address

spring:
  application:
    name: cloud-address
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8899
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.github.cloud.address.controller.*: debug
