server:
  port: 3001

eureka:
  instance:
    hostname: eureka3001.com
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka3002.com:3002/eureka/

spring:
  application:
    name: eureka-server3001
