server:
  port: 3002

eureka:
  instance:
    hostname: eureka3002.com
    #eureka中实例名称
    instance-id: eureka-server3002
    #eureka中实例IP
    prefer-ip-address: true
  client:
    #是否注册eureka自身
    register-with-eureka: true
    #是否从其他eureka节点获取服务注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka3001.com:3001/eureka/

spring:
  application:
    name: eureka-server
