server:
  port: 3002

eureka:
  instance:
    hostname: eureka3002.com
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka3001.com:3001/eureka/

spring:
  application:
    name: eureka-server3002
